import {
  Award,
  Bell,
  BookOpen,
  Calendar,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Download,
  Eye,
  Folder,
  GraduationCap,
  HelpCircle,
  Info,
  LayoutDashboard,
  LifeBuoy,
  LogOut,
  Mail,
  Megaphone,
  MessageSquare,
  Plus,
  Search,
  Trash2,
  Upload,
  User,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "book-open": BookOpen,
  video: Video,
  "clipboard-list": ClipboardList,
  "help-circle": HelpCircle,
  award: Award,
  "message-square": MessageSquare,
  megaphone: Megaphone,
  calendar: Calendar,
  folder: Folder,
  "life-buoy": LifeBuoy,
  users: Users,
  info: Info,
  upload: Upload,
};

export function DashboardIcon({ name, className }: { name: string; className?: string }) {
  const Icon = iconMap[name] ?? LayoutDashboard;
  return <Icon className={className} size={18} />;
}

export {
  Award,
  Bell,
  BookOpen,
  Calendar,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Download,
  Eye,
  Folder,
  GraduationCap,
  HelpCircle,
  Info,
  LayoutDashboard,
  LifeBuoy,
  LogOut,
  Mail,
  Megaphone,
  MessageSquare,
  Plus,
  Search,
  Trash2,
  Upload,
  User,
  Users,
  Video,
};
